services:
  isaacsim:
    env_file: .env.base
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ISAACSIM_BASE_IMAGE: ${ISAACSIM_BASE_IMAGE:-nvcr.io/nvidia/isaac-sim:5.1.0}
    image: berkeley-humanoid-lite-isaacsim:5.1.0
    container_name: berkeley-humanoid-lite-isaacsim
    gpus: all
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.Xauthority
      UV_CACHE_DIR: /workspace/docker/artifacts/uv/cache
      UV_LINK_MODE: copy
      UV_PYTHON_INSTALL_DIR: /workspace/docker/artifacts/uv/python
      UV_PROJECT_ENVIRONMENT: /home/ubuntu/.venv/berkeley-humanoid-lite
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace
      - berkeley-humanoid-lite-venv:/home/ubuntu/.venv
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.Xauthority:ro
    working_dir: /workspace

volumes:
  berkeley-humanoid-lite-venv:
